# Generated by Django 3.2.1 on 2021-05-10 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0003_auto_20210507_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpushinfo',
            old_name='account_id',
            new_name='account',
        ),
    ]
