# Generated by Django 3.2.1 on 2021-05-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appnotice',
            name='contents',
            field=models.TextField(verbose_name='공지 내용'),
        ),
        migrations.AlterField(
            model_name='appnotice',
            name='title',
            field=models.CharField(max_length=300, verbose_name='공지 제목'),
        ),
    ]
