# Generated by Django 3.2.1 on 2021-05-10 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked', through='bookstores.UserLikedBookstore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookstore',
            name='subscribed_users',
            field=models.ManyToManyField(related_name='subscribed', through='bookstores.SubscribeInfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
