# Generated by Django 3.2.1 on 2021-05-20 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstores', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='account',
            field=models.OneToOneField(db_column='account_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookstore', to=settings.AUTH_USER_MODEL, verbose_name='유저 계정 정보'),
        ),
    ]
