# Generated by Django 3.2.1 on 2021-05-14 04:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookstores', '0002_auto_20210510_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='영업 끝나는 시간'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookstore',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='영업 시작 시간'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BookstoreCategory',
            fields=[
                ('bookstores_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_type', models.CharField(max_length=30, verbose_name='카테고리명')),
                ('bookstore', models.ForeignKey(db_column='bookstore_id', on_delete=django.db.models.deletion.CASCADE, to='bookstores.bookstore', verbose_name='서점')),
            ],
            options={
                'verbose_name': '서점 카테고리',
                'verbose_name_plural': '서점 카테고리',
                'ordering': ['-bookstores_category_id'],
            },
        ),
    ]
