# Generated by Django 3.2.1 on 2021-05-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210514_1736'),
        ('bookstores', '0003_auto_20210514_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='book_stock',
            field=models.ManyToManyField(related_name='bookstore', through='books.BookStock', to='books.Books'),
        ),
    ]
