# Generated by Django 3.2.1 on 2021-05-31 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstores', '0004_auto_20210520_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='카테고리명')),
            ],
            options={
                'verbose_name': '카테고리 분류',
                'verbose_name_plural': '카테고리 분류',
                'ordering': ['-category_id'],
            },
        ),
        migrations.RemoveField(
            model_name='bookstorecategory',
            name='category_type',
        ),
        migrations.AddField(
            model_name='bookstorecategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='bookstores.category', verbose_name='카테고리'),
        ),
    ]
