# Generated by Django 3.2.1 on 2021-05-31 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_categorysubscribe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstores', '0005_auto_20210531_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='account',
            field=models.ManyToManyField(related_name='subscribe_category', through='profiles.CategorySubscribe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='bookstore',
            field=models.ManyToManyField(related_name='category', through='bookstores.BookstoreCategory', to='bookstores.Bookstore'),
        ),
    ]
