# Generated by Django 3.2.1 on 2021-05-17 03:41

import apps.accounts.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_staff', models.BooleanField(default=False, verbose_name='관리자 페이지 접근 권한')),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='이메일')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='휴대폰 번호')),
                ('status', model_utils.fields.StatusField(choices=[('USE', 'USE'), ('DELETED', 'DELETED'), ('DORMANT', 'DORMANT')], default='USE', help_text='USE - 사용 / DELETED - 탈퇴 / DORMANT - 휴면', max_length=30, no_check_for_status=True, verbose_name='계정 상태')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '유저 계정 정보',
                'verbose_name_plural': '유저 계정 정보',
                'ordering': ['-account_id'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserCertification',
            fields=[
                ('account', models.OneToOneField(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='certification', serialize=False, to='accounts.useraccount', verbose_name='유저 계정 정보')),
                ('is_sms_verified', models.BooleanField(default=False, verbose_name='SMS 인증 여부')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='이메일 인증 여부')),
                ('sms_code', models.CharField(max_length=6, null=True, verbose_name='SMS 인증 코드')),
                ('email_code', models.CharField(max_length=6, null=True, verbose_name='이메일 인증 코드')),
                ('sms_time_limit', models.DateTimeField(null=True, verbose_name='SMS 인증 제한 일시')),
                ('email_time_limit', models.DateTimeField(null=True, verbose_name='이메일 인증 제한 일시')),
            ],
            options={
                'verbose_name': '유저 인증 정보',
                'verbose_name_plural': '유저 인증 정보',
                'ordering': ['-account'],
            },
        ),
    ]
