# Generated by Django 3.2.1 on 2021-05-20 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercertification',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='certification', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='유저 계정 정보'),
        ),
    ]
