# Generated by Django 3.2.1 on 2021-05-07 07:09

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='USE', max_length=30, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='MALE', max_length=30, no_check_for_status=True),
        ),
    ]
