# Generated by Django 3.2.1 on 2021-05-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usercertification_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='status',
            field=models.CharField(choices=[('USE', '사용'), ('DELETED', '탈퇴'), ('DORMANT', '휴면')], default='USE', max_length=30, verbose_name='계정 상태'),
        ),
    ]
