# Generated by Django 3.2.1 on 2021-05-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210507_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='account',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cat_img_file',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cat_sound_file',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_img_file',
        ),
        migrations.DeleteModel(
            name='OwnerUserProfile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
