# Generated by Django 3.2.1 on 2021-06-09 01:58

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210608_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('certification_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_verified', models.BooleanField(default=False, verbose_name='인증 여부')),
                ('certification_type', models.CharField(choices=[('EMAIL', '이메일'), ('SMS', '핸드폰')], max_length=30, verbose_name='인증 타입')),
                ('address', models.CharField(help_text='이메일 주소 혹은 핸드폰 번호', max_length=50, verbose_name='인증 주소')),
                ('code', models.CharField(max_length=6, verbose_name='인증 코드')),
                ('limit_time', models.DateTimeField(verbose_name='인증 제한 일시')),
            ],
            options={
                'verbose_name': '인증 정보',
                'verbose_name_plural': '인증 정보',
                'ordering': ['-certification_id'],
            },
        ),
        migrations.DeleteModel(
            name='UserCertification',
        ),
    ]
