# Generated by Django 3.2.1 on 2021-05-07 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210507_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='관리자 페이지 접근 권한'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='휴대폰 번호'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='USE', help_text='USE - 사용 / DELETED - 탈퇴 / DORMANT - 휴면', max_length=30, no_check_for_status=True, verbose_name='계정 상태'),
        ),
        migrations.AlterField(
            model_name='usercertification',
            name='account',
            field=models.OneToOneField(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='유저 계정 정보'),
        ),
        migrations.AlterField(
            model_name='usercertification',
            name='email_code',
            field=models.CharField(max_length=6, null=True, verbose_name='이메일 인증 코드'),
        ),
        migrations.AlterField(
            model_name='usercertification',
            name='email_time_limit',
            field=models.DateTimeField(null=True, verbose_name='이메일 인증 제한 일시'),
        ),
        migrations.AlterField(
            model_name='usercertification',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='이메일 인증 여부'),
        ),
        migrations.AlterField(
            model_name='usercertification',
            name='is_sms_verified',
            field=models.BooleanField(default=False, verbose_name='SMS 인증 여부'),
        ),
        migrations.AlterField(
            model_name='usercertification',
            name='sms_code',
            field=models.CharField(max_length=6, null=True, verbose_name='SMS 인증 코드'),
        ),
        migrations.AlterField(
            model_name='usercertification',
            name='sms_time_limit',
            field=models.DateTimeField(null=True, verbose_name='SMS 인증 제한 일시'),
        ),
    ]
