# Generated by Django 3.2.1 on 2021-06-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='도서 제목')),
                ('contents', models.TextField(verbose_name='도서 소개')),
                ('isbn', models.CharField(help_text='ISBN10 또는 ISBN13 중 하나 이상 포함. 두 값이 모두 제공될 경우 공백으로 구분', max_length=25, verbose_name='ISBN 코드')),
                ('detail_url', models.URLField(max_length=500, verbose_name='도서 상세 URL')),
                ('publication_date', models.DateTimeField(help_text='ISO 8601 형식, [YYYY]-[MM]-[DD]T[hh]:[mm]:[ss].000+[tz]', verbose_name='도서 출판 일시')),
                ('authors', models.CharField(help_text='여러 명일 경우 ,으로 구분', max_length=300, verbose_name='도서 저자')),
                ('publisher', models.CharField(max_length=100, verbose_name='도서 출판사')),
                ('translators', models.CharField(help_text='여러 명일 경우 ,으로 구분', max_length=300, verbose_name='도서 번역가')),
                ('price', models.IntegerField(verbose_name='도서 정가')),
                ('sale_price', models.IntegerField(verbose_name='도서 판매가')),
                ('thumbnail', models.URLField(max_length=500, null=True, verbose_name='도서 표지 미리보기 URL')),
            ],
            options={
                'verbose_name': '도서 정보',
                'verbose_name_plural': '도서 정보',
                'ordering': ['-book_id'],
            },
        ),
    ]
