# Generated by Django 3.2.1 on 2021-05-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210507_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0, verbose_name='수량')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='추천도서 여부')),
            ],
            options={
                'verbose_name': '서점 별 책 재고',
                'verbose_name_plural': '서점 별 책 재고',
                'ordering': ['-stock_id'],
            },
        ),
        migrations.RenameModel(
            old_name='BooksInfo',
            new_name='Books',
        ),
    ]
