# Generated by Django 3.2.1 on 2021-05-14 08:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookstores', '0003_auto_20210514_1346'),
        ('books', '0003_auto_20210514_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstock',
            name='book',
            field=models.ForeignKey(db_column='book_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='books.books', verbose_name='책'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookstock',
            name='bookstore',
            field=models.ForeignKey(db_column='bookstore_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='bookstores.bookstore', verbose_name='서점'),
            preserve_default=False,
        ),
    ]
