# Generated by Django 3.2.1 on 2021-05-10 07:06

from django.conf import settings
from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='apply_users',
            field=models.ManyToManyField(related_name='apply_users', through='meetings.MeetingAttendApply', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingattendapply',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='WAITTING', help_text='WAITTING - 대기 / ACCEPTED - 수락 / CANCLED - 취소 / FAILED - 실패 (에러 등으로)', max_length=30, no_check_for_status=True, verbose_name='신청 상태'),
        ),
    ]
