# Generated by Django 3.2.1 on 2021-06-01 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookstores', '0001_initial'),
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='사용자 명')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='사용자 생년월일')),
                ('nickname', models.CharField(blank=True, max_length=30, null=True, verbose_name='사용자 닉네임')),
                ('gender', model_utils.fields.StatusField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], default=None, max_length=30, no_check_for_status=True, null=True, verbose_name='사용자 성별')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('cat_sound_file', models.ForeignKey(blank=True, db_column='cat_sound_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_sound_file', to='files.file', verbose_name='고양이 사운드 파일')),
                ('profile_img_file', models.ForeignKey(blank=True, db_column='profile_img_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_img_file', to='files.file', verbose_name='프로필 이미지 파일')),
            ],
            options={
                'verbose_name': '일반 유저 프로필 정보',
                'verbose_name_plural': '일반 유저 프로필 정보',
                'ordering': ['-profile_id'],
            },
        ),
        migrations.CreateModel(
            name='OwnerUserProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='사용자 명')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='사용자 생년월일')),
                ('nickname', models.CharField(blank=True, max_length=30, null=True, verbose_name='사용자 닉네임')),
                ('gender', model_utils.fields.StatusField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], default=None, max_length=30, no_check_for_status=True, null=True, verbose_name='사용자 성별')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
                ('cat_sound_file', models.ForeignKey(blank=True, db_column='cat_sound_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_cat_sound_file', to='files.file', verbose_name='고양이 사운드 파일')),
                ('profile_img_file', models.ForeignKey(blank=True, db_column='profile_img_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_profile_img_file', to='files.file', verbose_name='프로필 이미지 파일')),
            ],
            options={
                'verbose_name': '사장님 프로필 정보',
                'verbose_name_plural': '사장님 프로필 정보',
                'ordering': ['-profile_id'],
            },
        ),
        migrations.CreateModel(
            name='CategorySubscribe',
            fields=[
                ('category_subscribe_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자 계정 정보')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstores.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '사용자 카테고리 구독 정보',
                'verbose_name_plural': '사용자 카테고리 구독 정보',
                'ordering': ['-category_subscribe_id'],
            },
        ),
    ]
