# Generated by Django 3.2.1 on 2021-05-07 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0003_alter_file_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('birth', models.DateField()),
                ('nickname', models.CharField(max_length=30)),
                ('gender', model_utils.fields.StatusField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], default='MALE', max_length=30, no_check_for_status=True)),
                ('account', models.OneToOneField(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cat_img_file', models.ForeignKey(db_column='cat_img_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_img_file', to='files.file')),
                ('cat_sound_file', models.ForeignKey(db_column='cat_sound_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_sound_file', to='files.file')),
                ('profile_img_file', models.ForeignKey(db_column='profile_img_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_img_file', to='files.file')),
            ],
            options={
                'verbose_name': '일반 유저 프로필 정보',
                'verbose_name_plural': '일반 유저 프로필 정보',
                'ordering': ['-profile_id'],
            },
        ),
        migrations.CreateModel(
            name='OwnerUserProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('birth', models.DateField()),
                ('nickname', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=30)),
                ('account', models.OneToOneField(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cat_img_file', models.ForeignKey(db_column='cat_img_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_cat_img_file', to='files.file')),
                ('cat_sound_file', models.ForeignKey(db_column='cat_sound_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_cat_sound_file', to='files.file')),
                ('profile_img_file', models.ForeignKey(db_column='profile_img_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_profile_img_file', to='files.file')),
            ],
            options={
                'verbose_name': '사장님 프로필 정보',
                'verbose_name_plural': '사장님 프로필 정보',
                'ordering': ['-profile_id'],
            },
        ),
    ]
