# Generated by Django 3.2.1 on 2021-05-17 04:33

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owneruserprofile',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='사용자 생년월일'),
        ),
        migrations.AlterField(
            model_name='owneruserprofile',
            name='gender',
            field=model_utils.fields.StatusField(blank=True, choices=[(0, 'dummy')], default='MALE', max_length=30, no_check_for_status=True, null=True, verbose_name='사용자 성별'),
        ),
        migrations.AlterField(
            model_name='owneruserprofile',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='사용자 명'),
        ),
        migrations.AlterField(
            model_name='owneruserprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='사용자 닉네임'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='사용자 생년월일'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=model_utils.fields.StatusField(blank=True, choices=[(0, 'dummy')], default='MALE', max_length=30, no_check_for_status=True, null=True, verbose_name='사용자 성별'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='사용자 명'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='사용자 닉네임'),
        ),
    ]
