# Generated by Django 3.2.1 on 2021-05-17 04:54

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210517_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owneruserprofile',
            name='gender',
            field=model_utils.fields.StatusField(blank=True, choices=[(0, 'dummy')], default=None, max_length=30, no_check_for_status=True, null=True, verbose_name='사용자 성별'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=model_utils.fields.StatusField(blank=True, choices=[(0, 'dummy')], default=None, max_length=30, no_check_for_status=True, null=True, verbose_name='사용자 성별'),
        ),
    ]
