# Generated by Django 3.2.1 on 2021-05-14 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210511_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owneruserprofile',
            name='cat_img_file',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cat_img_file',
        ),
    ]
