# Generated by Django 3.2.1 on 2021-05-31 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstores', '0005_auto_20210531_1630'),
        ('profiles', '0004_auto_20210520_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySubscribe',
            fields=[
                ('category_subscribe_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자 계정 정보')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstores.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '사용자 카테고리 구독 정보',
                'verbose_name_plural': '사용자 카테고리 구독 정보',
                'ordering': ['-category_subscribe_id'],
            },
        ),
    ]
