# Generated by Django 3.2.1 on 2021-05-17 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookstores', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0, verbose_name='수량')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='추천도서 여부')),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='books.books', verbose_name='책')),
                ('bookstore', models.ForeignKey(db_column='bookstore_id', on_delete=django.db.models.deletion.CASCADE, to='bookstores.bookstore', verbose_name='서점')),
            ],
            options={
                'verbose_name': '서점 별 책 재고',
                'verbose_name_plural': '서점 별 책 재고',
                'ordering': ['-stock_id'],
            },
        ),
    ]
