# Generated by Django 3.2.1 on 2021-05-17 04:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookstores', '0002_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='상품 명')),
                ('contents', models.TextField(verbose_name='상품 설명')),
                ('price', models.IntegerField(verbose_name='상품 가격')),
                ('product_type', models.CharField(max_length=30, verbose_name='상품 타입')),
                ('bookstore', models.ForeignKey(db_column='bookstore_id', on_delete=django.db.models.deletion.CASCADE, to='bookstores.bookstore', verbose_name='서점')),
            ],
            options={
                'verbose_name': '서점 별 상품관리',
                'verbose_name_plural': '서점 별 상품관리',
                'ordering': ['-product_id'],
            },
        ),
    ]
