# Generated by Django 3.2.1 on 2021-05-20 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('bookstores', '0004_auto_20210520_1455'),
        ('products', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstock',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books', verbose_name='책'),
        ),
        migrations.AlterField(
            model_name='bookstock',
            name='bookstore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstores.bookstore', verbose_name='서점'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bookstore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstores.bookstore', verbose_name='서점'),
        ),
    ]
