# Generated by Django 3.2.1 on 2021-06-01 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPushInfo',
            fields=[
                ('registration_token', models.CharField(max_length=500, primary_key=True, serialize=False, verbose_name='파이어베이스 토큰')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저 계정 정보')),
            ],
            options={
                'verbose_name': '유저 푸시 정보',
                'verbose_name_plural': '유저 푸시 정보',
                'ordering': ['-account_id'],
            },
        ),
    ]
