# Generated by Django 3.2.1 on 2021-05-20 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='path',
            new_name='file',
        ),
    ]
