# Generated by Django 3.2.1 on 2021-05-20 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_rename_path_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.filegroup', verbose_name='파일 그룹'),
        ),
    ]
