# Generated by Django 3.2.1 on 2021-05-24 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_file_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='files.filegroup', verbose_name='파일 그룹'),
        ),
    ]
