# Generated by Django 3.2.1 on 2021-05-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_file_file_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(max_length=500, upload_to='%Y/%m/%d/', verbose_name='저장된 파일 경로 (파일 업로드)'),
        ),
    ]
