# Generated by Django 3.2.1 on 2021-05-11 04:15

from django.db import migrations, models
from ... import files


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0008_alter_file_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="path",
            field=models.FileField(
                max_length=500,
                upload_to=files.utils.upload_to_file,
                verbose_name="저장된 파일 경로 (파일 업로드)",
            ),
        ),
    ]
