# Generated by Django 3.2.1 on 2021-05-11 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_alter_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='origin_path',
        ),
    ]
