# Generated by Django 3.2.1 on 2021-05-07 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filegroup',
            options={'ordering': ['-created'], 'verbose_name': '파일 그룹', 'verbose_name_plural': '파일 그룹'},
        ),
    ]
