# Generated by Django 3.2.1 on 2021-05-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_filegroup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(max_length=260, upload_to='img'),
        ),
    ]
