# Generated by Django 3.2.1 on 2021-05-07 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_group',
            field=models.ForeignKey(db_column='file_group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.filegroup', verbose_name='파일 그룹'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(max_length=30, verbose_name='파일 확장자'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=500, verbose_name='저장된 파일명'),
        ),
        migrations.AlterField(
            model_name='file',
            name='order',
            field=models.IntegerField(default=1, help_text='묶음 파일일 경우 적용됩니다.', null=True, verbose_name='파일 정렬 순'),
        ),
        migrations.AlterField(
            model_name='file',
            name='origin_name',
            field=models.CharField(max_length=500, verbose_name='원본 파일명'),
        ),
        migrations.AlterField(
            model_name='file',
            name='origin_path',
            field=models.CharField(max_length=500, verbose_name='원본 파일 경로'),
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(max_length=500, upload_to='img', verbose_name='저장된 파일 경로 (파일 업로드)'),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(verbose_name='파일 크기'),
        ),
    ]
