# Generated by Django 3.2.1 on 2021-05-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20210507_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(max_length=500, upload_to='files/', verbose_name='저장된 파일 경로 (파일 업로드)'),
        ),
    ]
