# Generated by Django 3.2.1 on 2021-05-11 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20210511_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_group',
            field=models.ForeignKey(blank=True, db_column='file_group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.filegroup', verbose_name='파일 그룹'),
        ),
    ]
