# Generated by Django 3.2.1 on 2021-06-01 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookstores', '0001_initial'),
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='모임 이름')),
                ('introduction', models.CharField(max_length=500, verbose_name='모임 설명')),
                ('people_max_cnt', models.IntegerField(verbose_name='모임 인원 제한')),
                ('metting_type', models.CharField(max_length=30, verbose_name='모임 종류')),
                ('price', models.IntegerField(verbose_name='모임 가격')),
                ('meeting_date', models.DateField(verbose_name='모임 날짜')),
                ('start_time', models.TimeField(verbose_name='모임 시작 시간')),
                ('end_time', models.TimeField(verbose_name='모임 종료 시간')),
                ('status', model_utils.fields.StatusField(choices=[('CAN_APPLY', 'CAN_APPLY'), ('FULL', 'FULL'), ('CANT_APPLY', 'CANT_APPLY')], default='CAN_APPLY', help_text='CAN_APPLY - 신청가능 / FULL - 만원 마감 / CANT_APPLY - 모집 마감(사장님이 중단하거나, 기간 만료일 경우)', max_length=30, no_check_for_status=True, verbose_name='모임 신청 상태')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사장님 계정 정보')),
            ],
            options={
                'verbose_name': '모임',
                'verbose_name_plural': '모임',
                'ordering': ['-meeting_id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendApply',
            fields=[
                ('apply_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', model_utils.fields.StatusField(choices=[('WAITTING', 'WAITTING'), ('ACCEPTED', 'ACCEPTED'), ('CANCLED', 'CANCLED'), ('FAILED', 'FAILED')], default='WAITTING', help_text='WAITTING - 대기 / ACCEPTED - 수락 / CANCLED - 취소 / FAILED - 실패 (에러 등으로)', max_length=30, no_check_for_status=True, verbose_name='신청 상태')),
                ('err_msg', models.CharField(max_length=500, verbose_name='에러 메세지')),
                ('apply_date', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='신청 일시')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='신청한 유저의 계정 정보')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='모임 정보')),
            ],
            options={
                'verbose_name': '모임 참가 신청',
                'verbose_name_plural': '모임 참가 신청',
                'ordering': ['-apply_id'],
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='apply_users',
            field=models.ManyToManyField(related_name='apply_meeting', through='meetings.MeetingAttendApply', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='bookstore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstores.bookstore', verbose_name='서점 정보'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='img_file_group',
            field=models.ForeignKey(db_column='img_file_group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.filegroup', verbose_name='모임 이미지 묶음 파일 정보'),
        ),
    ]
