# Generated by Django 3.2.1 on 2021-05-20 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='apply_users',
            field=models.ManyToManyField(related_name='apply_meeting', through='meetings.MeetingAttendApply', to=settings.AUTH_USER_MODEL),
        ),
    ]
