# Generated by Django 3.2.1 on 2021-05-20 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstores', '0004_auto_20210520_1455'),
        ('meetings', '0002_alter_meeting_apply_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사장님 계정 정보'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='bookstore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstores.bookstore', verbose_name='서점 정보'),
        ),
        migrations.AlterField(
            model_name='meetingattendapply',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='신청한 유저의 계정 정보'),
        ),
        migrations.AlterField(
            model_name='meetingattendapply',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='모임 정보'),
        ),
    ]
