# Generated by Django 3.2.1 on 2021-05-14 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0002_auto_20210510_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='apply_users',
            field=models.ManyToManyField(related_name='meetting', through='meetings.MeetingAttendApply', to=settings.AUTH_USER_MODEL),
        ),
    ]
