# Generated by Django 3.2.1 on 2021-05-07 09:09

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20210507_1809'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owneruserprofile',
            name='birth',
            field=models.DateField(verbose_name='사용자 생년월일'),
        ),
        migrations.AlterField(
            model_name='owneruserprofile',
            name='cat_img_file',
            field=models.ForeignKey(db_column='cat_img_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_cat_img_file', to='files.file', verbose_name='고양이 이미지 파일'),
        ),
        migrations.AlterField(
            model_name='owneruserprofile',
            name='cat_sound_file',
            field=models.ForeignKey(db_column='cat_sound_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_cat_sound_file', to='files.file', verbose_name='고양이 사운드 파일'),
        ),
        migrations.AlterField(
            model_name='owneruserprofile',
            name='gender',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='MALE', max_length=30, no_check_for_status=True, verbose_name='사용자 성별'),
        ),
        migrations.AlterField(
            model_name='owneruserprofile',
            name='name',
            field=models.CharField(max_length=30, verbose_name='사용자 명'),
        ),
        migrations.AlterField(
            model_name='owneruserprofile',
            name='nickname',
            field=models.CharField(max_length=30, verbose_name='사용자 닉네임'),
        ),
        migrations.AlterField(
            model_name='owneruserprofile',
            name='profile_img_file',
            field=models.ForeignKey(db_column='profile_img_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_profile_img_file', to='files.file', verbose_name='프로필 이미지 파일'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth',
            field=models.DateField(verbose_name='사용자 생년월일'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cat_img_file',
            field=models.ForeignKey(db_column='cat_img_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_img_file', to='files.file', verbose_name='고양이 이미지 파일'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cat_sound_file',
            field=models.ForeignKey(db_column='cat_sound_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_sound_file', to='files.file', verbose_name='고양이 사운드 파일'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='MALE', max_length=30, no_check_for_status=True, verbose_name='사용자 성별'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=30, verbose_name='사용자 명'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(max_length=30, verbose_name='사용자 닉네임'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img_file',
            field=models.ForeignKey(db_column='profile_img_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_img_file', to='files.file', verbose_name='프로필 이미지 파일'),
        ),
    ]
