# Generated by Django 3.2.1 on 2021-05-11 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_file_file_group'),
        ('profiles', '0003_auto_20210510_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owneruserprofile',
            name='cat_img_file',
            field=models.ForeignKey(blank=True, db_column='cat_img_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_cat_img_file', to='files.file', verbose_name='고양이 이미지 파일'),
        ),
        migrations.AlterField(
            model_name='owneruserprofile',
            name='cat_sound_file',
            field=models.ForeignKey(blank=True, db_column='cat_sound_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_cat_sound_file', to='files.file', verbose_name='고양이 사운드 파일'),
        ),
        migrations.AlterField(
            model_name='owneruserprofile',
            name='profile_img_file',
            field=models.ForeignKey(blank=True, db_column='profile_img_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_profile_img_file', to='files.file', verbose_name='프로필 이미지 파일'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cat_img_file',
            field=models.ForeignKey(blank=True, db_column='cat_img_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_img_file', to='files.file', verbose_name='고양이 이미지 파일'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cat_sound_file',
            field=models.ForeignKey(blank=True, db_column='cat_sound_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_sound_file', to='files.file', verbose_name='고양이 사운드 파일'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img_file',
            field=models.ForeignKey(blank=True, db_column='profile_img_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_img_file', to='files.file', verbose_name='프로필 이미지 파일'),
        ),
    ]
