# Generated by Django 3.2.1 on 2021-05-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksInfo',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('contents', models.TextField()),
                ('isbn', models.CharField(help_text='ISBN10 또는 ISBN13 중 하나 이상 포함. 두 값이 모두 제공될 경우 공백으로 구분', max_length=25)),
                ('detail_url', models.URLField(max_length=500)),
                ('publication_date', models.DateTimeField(help_text='ISO 8601 형식, [YYYY]-[MM]-[DD]T[hh]:[mm]:[ss].000+[tz]')),
                ('authors', models.CharField(help_text='여러 명일 경우 ,으로 구분', max_length=300)),
                ('publisher', models.CharField(max_length=100)),
                ('translators', models.CharField(help_text='여러 명일 경우 ,으로 구분', max_length=300)),
                ('price', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('thumbnail', models.URLField(max_length=500, null=True)),
            ],
            options={
                'verbose_name': '도서 정보',
                'verbose_name_plural': '도서 정보',
                'ordering': ['-book_id'],
            },
        ),
    ]
